PlayerBots = {}
L = setmetatable({}, {
	__index = function(t, k)
		error("Locale key " .. tostring(k ) .. " is not provided.")
	end
} )
function PlayerBots:UpdateLocale(loc)
	for k, v in pairs(loc) do
		if v == true then
			L[k] = k
		else
			L[k] = v
		end
	end
end

PlayerBots:UpdateLocale( {
    ["Bring bot online"] = true,
    ["Logout bot"] = true,
    ["Invite to your group"] = true,
    ["Remove from group"] = true,
    ["Start whisper chat"] = true,
    ["Bring all bots online"] = true,
    ["Logout all bots"] = true,
    ["Invite all bots to your group"] = true,
    ["Remove all bots from group"] = true,
    ["Follow"] = true,
    ["Stay"] = true,
    ["Set guard position"] = true,
    ["Guard"] = true,
    ["Aggresive mode"] = true,
    ["Passive mode"] = true,
    ["Reset movement"] = true,
    ["Stats"] = true,
    ["Loot"] = true,
    ["Loot (if looting) normal"] = true,
    ["Loot (if looting) everything"] = true,
    ["Loot (if looting) disenchant"] = true,
    ["Loot (if looting) gray"] = true,
    ["Loot (if looting) profession"] = true,
    ["Reset actions"] = true,
    ["Formation near"] = true,
    ["Formation melee"] = true,
    ["Formation line"] = true,
    ["Formation circle"] = true,
    ["Formation arrow"] = true,
    ["Formation far"] = true,
    ["Formation chaos"] = true,
    ["Reset formations"] = true,
    ["Play as primary tank"] = true,
    ["Play as secondary tank"] = true,
    ["Play as DPS"] = true,
    ["Play as caster DPS"] = true,
    ["Reset attacktype"] = true,
    ["Attack enemy with assigned mark"] = true,
    ["Assign skull mark"] = true,
    ["Assign cross mark"] = true,
    ["Assign circle mark"] = true,
    ["Assign star mark"] = true,
    ["Assign square mark"] = true,
    ["Assign triangle mark"] = true,
    ["Assign diamond mark"] = true,
    ["Assign moon mark"] = true,
    ["Use health and mana potions"] = true,
    ["Use food and drinks"] = true,
    ["Cast long spells cautiously"] = true,
    ["Conserve mana"] = true,
    ["Cast buffs"] = true,
    ["Attack weak enemy first"] = true,
    ["Keep threat level low"] = true,
    ["Say custom lines"] = true,
    ["Reset generic"] = true,
    ["Use bear form"] = true,
    ["Use cat form"] = true,
    ["Use owl form"] = true,
    ["Healer mode"] = true,
    ["Reset class"] = true,
    ["DPS mode"] = true,
    ["Buff movement speed"] = true,
    ["Buff mana regen"] = true,
    ["Buff DPS"] = true,
    ["Reset class"] = true,
    ["Use arcane spells"] = true,
    ["Use fire spells"] = true,
    ["Use fire AOE abilities"] = true,
    ["Use frost spells"] = true,
    ["Use frost AOE abilities"] = true,
    ["Buff mana regen"] = true,
    ["Buff DPS"] = true,
    ["Reset class"] = true,
    ["DPS mode"] = true,
    ["Tank mode"] = true,
    ["Buff mana regen"] = true,
    ["Buff health regen"] = true,
    ["Buff DPS"] = true,
    ["Buff armor"] = true,
    ["Buff movement speed"] = true,
    ["Buff threat generation"] = true,
    ["Reset class"] = true,
    ["Healer mode"] = true,
    ["Use holy spells"] = true,
    ["Shadow"] = true,
    ["Use shadow AOE abilities"] = true,
    ["Use shadow debuffs"] = true,
    ["Reset class"] = true,
    ["DPS mode"] = true,
    ["Reset class"] = true,
    ["Caster mode"] = true,
    ["Use caster AOE abilities"] = true,
    ["Healer mode"] = true,
    ["Melee mode"] = true,
    ["Use totems"] = true,
    ["Buff mana regen"] = true,
    ["Buff DPS"] = true,
    ["Reset class"] = true,
    ["DPS mode"] = true,
    ["Use DPS debuffs"] = true,
    ["Use AOE abilities"] = true,
    ["Tank mode"] = true,
    ["Reset class"] = true,
    ["DPS mode"] = true,
    ["Use AOE abilities"] = true,
    ["Tank mode"] = true,
    ["Reset class"] = true
} )
